export interface CalculatorSeoPage {
  slug: string
  id: string
  name: string
  title: string
  description: string
  intro: string
  howItWorks: string
  points: string[]
}

export const CALCULATOR_SEO_PAGES: CalculatorSeoPage[] = [
  {
    slug: "emi-calculator",
    id: "emi",
    name: "EMI Calculator",
    title: "EMI Calculator for Home, Car & Personal Loans",
    description: "Calculate monthly EMI, total interest and total repayment for home, car and personal loans in India.",
    intro: "Use the EMI calculator to estimate your monthly loan payment before you compare lenders. Enter the loan amount, annual interest rate and tenure to see a complete repayment breakdown.",
    howItWorks: "The calculator uses the standard reducing-balance EMI formula. Interest is applied to the outstanding principal each month, so the interest portion falls as the loan balance reduces.",
    points: ["Monthly EMI and total repayment", "Total interest paid across the loan", "Year-wise amortization schedule", "Custom amount, interest rate and tenure"],
  },
  {
    slug: "car-loan-calculator",
    id: "carloan",
    name: "Car Loan Calculator",
    title: "Car Loan EMI Calculator",
    description: "Estimate car loan EMI after down payment with a custom interest rate and repayment tenure.",
    intro: "Plan your next car purchase with a clear view of the loan amount, monthly EMI, total interest and repayment cost after your down payment.",
    howItWorks: "The on-road price minus your down payment becomes the financed loan amount. The EMI is then calculated using the standard reducing-balance formula.",
    points: ["On-road price and down payment", "Custom car-loan interest rate", "Monthly EMI and total cost", "Year-wise repayment schedule"],
  },
  {
    slug: "home-loan-eligibility-calculator",
    id: "eligibility",
    name: "Home Loan Eligibility Calculator",
    title: "Home Loan Eligibility Calculator",
    description: "Estimate home loan eligibility from monthly income, existing EMIs, interest rate and tenure.",
    intro: "Get a planning estimate of the home loan amount you may be able to service. Enter your net monthly income and existing EMIs, then adjust the rate and tenure.",
    howItWorks: "The estimate applies a 50% fixed-obligation-to-income assumption and subtracts existing EMIs before converting the remaining EMI capacity into a possible loan amount.",
    points: ["Income and existing EMI inputs", "Custom rate and tenure", "Estimated maximum EMI", "Loan amount and interest breakdown"],
  },
  {
    slug: "income-tax-calculator",
    id: "tax",
    name: "Income Tax Calculator",
    title: "Income Tax Calculator India — Old vs New Regime",
    description: "Compare estimated income tax under India's old and new tax regimes for FY 2025-26.",
    intro: "Compare your estimated tax under the old and new income-tax regimes. Enter gross annual income and eligible deductions to understand taxable income, rebate, cess and take-home pay.",
    howItWorks: "The calculator applies progressive slabs, standard deduction, eligible old-regime deductions, Section 87A rebate and 4% health and education cess. It is an estimate, not a tax filing or professional opinion.",
    points: ["Old and new regime comparison", "FY 2025-26 / AY 2026-27 slabs", "Deductions and standard deduction", "Tax, cess, rebate and take-home breakdown"],
  },
  {
    slug: "sip-calculator",
    id: "sip",
    name: "SIP Calculator",
    title: "SIP Calculator — Estimate Mutual Fund Returns",
    description: "Estimate SIP maturity value, invested amount and potential returns from monthly investments.",
    intro: "Plan a monthly mutual-fund investment with a simple SIP projection. Adjust the monthly contribution, expected annual return and investment period.",
    howItWorks: "The projection compounds a monthly investment at the expected monthly rate. Market-linked returns are not guaranteed, so use the result only for scenario planning.",
    points: ["Monthly investment amount", "Expected annual return", "Investment duration", "Invested amount and estimated gains"],
  },
  {
    slug: "lumpsum-calculator",
    id: "lumpsum",
    name: "Lumpsum Calculator",
    title: "Lumpsum Investment Calculator",
    description: "Estimate how a one-time investment could grow with a custom return rate and time period.",
    intro: "See how a one-time investment may grow over time. Enter the amount, expected annual return and investment period to compare possible outcomes.",
    howItWorks: "The calculator uses annual compound growth. Actual investment returns vary and may be negative, especially for market-linked products.",
    points: ["One-time investment amount", "Custom expected return", "Investment duration", "Estimated maturity and gain"],
  },
  {
    slug: "retirement-calculator",
    id: "retirement",
    name: "Retirement Calculator",
    title: "Retirement Calculator India",
    description: "Estimate the retirement corpus needed using current expenses, inflation, retirement age and life expectancy.",
    intro: "Build a retirement planning estimate from your current age, retirement age, monthly expenses, inflation and expected post-retirement return.",
    howItWorks: "Current expenses are inflated until retirement, then discounted against an inflation-adjusted post-retirement return for the expected retirement period.",
    points: ["Inflation-adjusted retirement expenses", "Retirement age and life expectancy", "Post-retirement return assumption", "Estimated corpus required"],
  },
  {
    slug: "nps-calculator",
    id: "nps",
    name: "NPS Calculator",
    title: "NPS Calculator — Corpus, Annuity & Pension Estimate",
    description: "Estimate NPS corpus, lump-sum withdrawal, annuity allocation and monthly pension.",
    intro: "Estimate how a regular NPS contribution may grow by retirement and see how the corpus could split between lump-sum withdrawal and annuity.",
    howItWorks: "The projection compounds monthly contributions using your expected return, then applies the selected annuity percentage and annuity rate.",
    points: ["Monthly NPS contribution", "Current age and retirement at 60", "Expected return and annuity share", "Corpus, lump sum and pension estimate"],
  },
  {
    slug: "ppf-calculator",
    id: "ppf",
    name: "PPF Calculator",
    title: "PPF Calculator — Public Provident Fund Maturity",
    description: "Estimate PPF maturity, total investment and interest using a custom annual contribution and rate.",
    intro: "Plan long-term PPF savings with an estimate of maturity value, total deposits and interest over the selected period.",
    howItWorks: "The estimate compounds annual contributions at the rate you enter. PPF rules, rates and deposit timing are governed by the government and may change.",
    points: ["Annual contribution up to the current PPF cap", "Minimum 15-year planning period", "Custom interest-rate scenario", "Maturity and interest breakdown"],
  },
  {
    slug: "fd-calculator",
    id: "fd",
    name: "FD Calculator",
    title: "FD Calculator — Fixed Deposit Maturity",
    description: "Calculate fixed-deposit maturity and interest with custom principal, rate and tenure.",
    intro: "Estimate the maturity value of a fixed deposit by entering your deposit amount, annual interest rate and tenure.",
    howItWorks: "The calculator uses quarterly compounding, a common convention for Indian bank fixed deposits. Your bank's exact product terms may differ.",
    points: ["Deposit amount and tenure", "Custom annual interest rate", "Quarterly compounding estimate", "Maturity and interest earned"],
  },
  {
    slug: "rd-calculator",
    id: "rd",
    name: "RD Calculator",
    title: "RD Calculator — Recurring Deposit Maturity",
    description: "Estimate recurring-deposit maturity from monthly deposit, interest rate and tenure.",
    intro: "Plan regular savings with an RD maturity estimate. Adjust the monthly deposit, annual rate and duration to see total deposits and interest.",
    howItWorks: "The estimate applies quarterly compounding to monthly deposits. Banks may calculate recurring-deposit interest using product-specific timing rules.",
    points: ["Monthly recurring deposit", "Custom annual interest rate", "Flexible investment period", "Maturity and interest estimate"],
  },
  {
    slug: "gst-calculator",
    id: "gst",
    name: "GST Calculator",
    title: "GST Calculator — Add or Remove GST",
    description: "Add GST to a net amount or remove GST from an inclusive price with a custom tax rate.",
    intro: "Calculate GST for an invoice, product or service. Choose whether your amount is before or after GST, then select a common slab or type a custom rate.",
    howItWorks: "For an exclusive amount, GST is added to the base. For an inclusive amount, the base is recovered by dividing the gross amount by one plus the GST rate.",
    points: ["GST-exclusive and GST-inclusive modes", "Common Indian GST slabs", "Custom GST rates", "Base, tax and total breakdown"],
  },
  {
    slug: "age-calculator",
    id: "age",
    name: "Age Calculator",
    title: "Age Calculator — Exact Age in Years, Months & Days",
    description: "Calculate exact age from date of birth, including total days lived and days until the next birthday.",
    intro: "Enter a date of birth to calculate exact age in years, months and days. The tool also estimates total days lived and time until the next birthday.",
    howItWorks: "The calculator compares the selected date of birth with today's date and handles month and year boundaries for a calendar-based result.",
    points: ["Exact age in years, months and days", "Total days lived", "Days until next birthday", "Date validation for future dates"],
  },
  {
    slug: "bill-split-calculator",
    id: "bill",
    name: "Bill Split Calculator",
    title: "Bill Split Calculator — Discount, GST, Tip & Service Charge",
    description: "Calculate a final bill after discount, GST, service charge and tip, then split it between people.",
    intro: "Work out the real amount to pay on a restaurant, shopping or service bill. Enter your own percentages and split the total between any number of people.",
    howItWorks: "The discount is applied first. Tax, service charge and tip are then calculated on the discounted amount and added to produce the final bill.",
    points: ["Discount and tax/GST percentage", "Service charge and tip", "Split between up to 50 people", "Total bill and per-person amount"],
  },
]
